pharma/urls.py
from django.urls import path
from . import views

app_name = 'pharma'

urlpatterns = [
    path('', views.billing, name='billing'),
    path('purchase', views.purchase, name='purchase'),
    path('products', views.view_products, name='products'),
    path('addmedicine', views.addmedicine, name='addmedicine'),
    path('addpharmacyst', views.add_pharmacyst, name='addpharmacyst'),
    path('price',views.price_show, name='price'),
    path('total',views.total, name='total'),
    # path('checkout',views.checkout, name='checkout'),
    path('gst',views.gst, name='gst'),
    path('grandtotal',views.grandtotal, name='grandtotal'),



  
]

pharmacy/urls.py
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns 
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pharma.urls')),
   

]

urlpatterns += staticfiles_urlpatterns()

pharma/models.py
from django.db import models

# Create your models here.

class Medicine(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100,)
    quantity = models.IntegerField()
    puchase_cost = models.FloatField()
    selling_cost = models.FloatField()


    class Meta:
        db_table = 'medicine'


class Bill(models.Model):
    bill_id = models.AutoField(primary_key=True)
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    qty = models.IntegerField()

    class Meta:
        db_table = 'bill'

pharma/views.py
from tokenize import Number
from unicodedata import name
from django.shortcuts import redirect, render
from django.http import JsonResponse


from pharma.models import Medicine

# Create your views here.
# def home(request):
#     return render(request,'home.html')

def addmedicine(request):
    msg = ""
    if request.method == 'POST':
        
        med_name = request.POST['name']
        qty = request.POST['qty']
        p_cost = request.POST['pcost']
        s_cost = request.POST['scost']

        new_med = Medicine(name=med_name,quantity=qty,puchase_cost=p_cost,selling_cost=s_cost)
        new_med.save()
        msg = "Medicine added successfully"

    return render(request,'addmed.html', {'msg':msg,})

def purchase(request):

    medicine = Medicine.objects.filter(quantity__lte=10)  #filter where quantity lessthan 10
    
    return render(request,'purchase.html',{'medicine':medicine,})

def view_products(request):
    medicine = Medicine.objects.all()
    return render(request,'allproducts.html',{'medicine':medicine,})

def add_pharmacyst(request):
    return render(request,'addpharmacyst.html')

def billing(request):
    medicine = Medicine.objects.all()

    if request.method == 'POST':
        mid = request.POST['medicine']
        qty = request.POST['qty']
        medicineqty = Medicine.objects.get(id=mid)

        medicineqty.quantity = medicineqty.quantity - int(qty)
        medicineqty.save()
        return render(request,'bill.html',{'medicine':medicine,})

        
    return render(request,'bill.html',{'medicine':medicine,})


def price_show(request):
    id = request.GET['id']
    # print(id)
    try:
        price = Medicine.objects.get(id=id)
        return render(request,'price.html',{'price':price.selling_cost})
    except:
        return render(request,'price.html',{'price':0})

def total(request):
    price = request.GET['price']
    qty = request.GET['qty']
    try:
        total_price = int(qty) * int(price)
        gst = (total_price * 5)/100
        grand_total = int(total_price+gst)
        # print(total_price)
        # print(gst)
        # print(grand_total)
        return render(request,'total.html',{'total_price':total_price,})
    except:
        return render(request,'total.html',{'total_price':0})


def gst(request):
    
    med = request.GET['id']
    qty = request.GET['qty']

    medid = Medicine.objects.get(id=med)
    cost = medid.selling_cost
    total = int(cost) * int(qty)
    gst = (total * 5)/100
    print(gst)

    return render(request,'gst.html',{'gst':gst,})

def grandtotal(request):
    
    med = request.GET['id']
    qty = request.GET['qty']

    medid = Medicine.objects.get(id=med)
    cost = medid.selling_cost
    total = int(cost) * int(qty)
    gst = (total * 5)/100
    gtotal = total + gst

    return render(request,'gtotal.html',{'gtotal':gtotal,})


    
# def checkout(request):
#     pass
    

pharma/templates/addmed.html
{% extends 'master.html' %}
{% block content %}
{% load static %}
<link href="{% static 'css/addmed.css'%}" rel="stylesheet">

    <div class="container-fluid">
        <div class="row">
            <div class="formadd">
                <p>
                    Add medicine
                </p>
                <form method="POST">
                {% csrf_token %}
                    <table class="addtable">
                        <tr>
                            <td>Medicine name</td>
                            <td>
                                <input type="text" name="name" placeholder="medicine name" style="text-transform: uppercase;">
                            </td>
                        </tr>
                        <tr>
                            <td>Quantity</td>
                            <td>
                                <input type="number" name="qty" placeholder="Quantity" min="0">

                            </td>
                        </tr>
                        <tr>
                            <td>Purchase cost</td>
                            <td>
                                <input type="number" name="pcost" placeholder="Purchase Cost" min="0">
                            </td>
                        </tr>
                        <tr>
                            <td>Selling cost</td>
                            <td>
                                <input type="number" name="scost" placeholder="Selling Cost" min="0">

                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <button>ADD</button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">{{msg}}</td>      
                        </tr>
                   </table>
                </form>
            </div>
        </div>
    </div>
    

{% endblock %}

pharma/templates/addpharmacyst.html
{% extends 'master.html' %}
{% block content %}
{% load static %}
<link href="{% static 'css/addpharma.css'%}" rel="stylesheet">


    
    <div class="container-fluid">
        <div class="row">
            <div class="addpharma">
                <p>
                    Add Pharmasyst
                </p>
                <form method="">
                    <table class="addphtable">
                        <tr>
                            <td>Name</td>
                            <td>
                                <input type="text" name="name" placeholder="medicine name">
                            </td>
                        </tr>
                        <tr>
                            <td>Contact Number</td>
                            <td>
                                <input type="number" name="phno" placeholder="Quantity">

                            </td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>
                                <input type="number" name="email" placeholder="Purchase Cost">
                            </td>
                        </tr>
                        <tr>
                            <td>genter</td>
                            <td>
                                <input type="radio" name="genter" value="male" placeholder="Selling Cost">
                                <input type="radio" name="genter" value="female" placeholder="Selling Cost">
                            </td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td>
                                <input type="text" name="psw" placeholder="Enter Password">
                            </td>
                        </tr>
                        <tr>
                            <td>Confirm Password</td>
                            <td>
                                <input type="text" name="c
                                
                                psw" placeholder="Confirm Password">
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <button>ADD</button>
                            </td>
                        </tr>
                   </table>
                </form>
            </div>
        </div>
    </div>
    

{% endblock %}

pharma/templates/allproducts.html
{% extends 'master.html' %}
{% block content %}


<table class="table center" style="margin-top: 40px;">
  <thead>
    <tr>
      <th scope="col">Medicine id</th>
      <th scope="col">Medicine Name</th>
      <th scope="col">Avilable quantity </th>
      <th scope="col">Purchase cost</th>
      <th scope="col">Selling cost</th>
      

    </tr>
  </thead>
  <tbody>
    {% for i in medicine %}
    <tr>
      <th scope="row">{{i.id}}</th>
      <td>{{i.name | upper}}</td>
      <td>{{i.quantity}}</td>
      <td>{{i.puchase_cost}}</td>
      <td>{{i.selling_cost}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

pharma/templates/bill.html
{% extends 'master.html' %}
{% block content %}
{% load static %}
<link href="{% static 'css/billing.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>

<div class="formbill">
    <form method="POST">
        {% csrf_token %}



        <h1
            style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; font-weight: bolder; margin-bottom: 40px;">
            PHARMA BILLING</h1>
        <label>Customer Name:</label><input type="text" style="margin-right: 250px;">
        <label>Phone number:</label><input type="number">
        <label style="margin-left: 660px; margin-top: 20px;">date:</label><input type="datetime">

        <table class="table" style="margin-top: 20px;">
            <tr>
                <th>Sl no</th>
                <th>Medicine Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Item Total</th>
            </tr>
            <tr>
                <th>1</th>
                <td>
                    <select name="medicine" id="medicine">
                    {% for m in medicine %}
                        <option value="{{m.id}}" id="mname">{{m.name}}</option>
                    {% endfor %}
                    </select>
                </td>
                <td>
                    <input type="number" min="1" max="{{m.quantity}}" id="qty" name="qty">
                </td>
                <td>

                    <input type="number"  name="price" id="price">
                </td>
                <td><input type="number" readonly name="total" id="total"></td>
            </tr>

        </table>
        <table style="float: right;">
            <tr>
                <td>GST:</td>
                <td><input type="text" id="gst">
                </td>
            </tr>
            <tr>
                <td>Grand Total:
                <td><input type="text" id="gtotal"></td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 20px;">
                        <button class="btn btn-primary" type="submit">GENERATE</button>
                    </div>
                </td>
            </tr>
        </table>

    </form>

    
</div>

<script>
    $(document).ready(function () {
        $('#medicine'). change(function () {
            // console.log('test')
            $.ajax({
                url: 'http://127.0.0.1:8000/price',
                data: {
                    'id': $(this).val()
                },
                type: 'get',
                success: function (response) {
                    // alert(response);
                    // $('#price').html(response)
                    var price = Number(response)
                    $('#price').val(price)
                    // document.getElementById('price').value=response;
                }
            })
        })
    })

    $(document).ready(function (){
        $('#qty').change(function (){
            $.ajax({
                url: 'http://127.0.0.1:8000/total',
                data: {
                    'qty': $(this).val() ,
                    'price': $('#price').val()

                },
                type: 'get',
                success: function (response) {
                   var total = Number(response)
                   $('#total').val(total)
                }
            })
            // alert(Number($('#price').val()) * Number($('qty').val()))
            // total=Number($('#price').val()) * Number($('qty').val())
            // $('#total').val(total)
        })

    })


    $(document).ready(function (){
        $('#qty').change(function (){
            $.ajax({
                url: 'http://127.0.0.1:8000/gst',
                data: {
                    'id': $('#medicine').val() ,
                    'qty': $('#qty').val() ,

                },
                type: 'get',
                success: function (response) {
                   var gst = Number(response)
                   $('#gst').val(gst)
                }
            })
            
        })

    })

    $(document).ready(function (){
        $('#qty').change(function (){
            $.ajax({
                url: 'http://127.0.0.1:8000/grandtotal',
                data: {
                    'id': $('#medicine').val() ,
                    'qty': $('#qty').val() ,

                },
                type: 'get',
                success: function (response) {
                   var gtotal = Number(response)
                   $('#gtotal').val(gtotal)
                }
            })
            
        })

    })



</script>

{% endblock %}

pharma/templates/gst.html
{{gst}}

pharma/templates/gtotal.html
{{gtotal}}

pharma/templates/home.html
{% extends 'master.html' %}
{% block content %}
{% load static %}
<link href="{% static 'css/addmed.css'%}" rel="stylesheet">

<div class="container-fluid">
    <div class="row">
       
    </div>
</div>

{% endblock %}

pharma/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>

        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none" style="margin-top: 20px;">
                            <span class="fs-5 d-none d-sm-inline"><h1>PHARMA</h1></span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                            <li class="nav-item">
                                <a href="{% url 'pharma:billing' %}" class="nav-link align-middle px-0">
                                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                                </a>
                            </li>
                            
                            <li>
                                <a href="{% url 'pharma:addpharmacyst' %}" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Pharmacyst</span> </a>
                                
                            </li>
                            <li>
                                <a href="{% url 'pharma:addmedicine' %}" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi bi-cart"></i> <span class="ms-1 d-none d-sm-inline">Add Medicine</span></a>
                            </li>
                            <li>
                                <a href="{% url 'pharma:purchase' %}"  class="nav-link px-0 align-middle ">
                                    <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Purchase list</span></a>
                                
                            </li>
                            <li>
                                <a href="{% url 'pharma:products' %}"  class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">View All Products</span> </a>
                                    
                            </li>
                            
                        </ul>
                        <hr>
                        
                    </div>
                </div>
                <div class="col py-3">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        

    </ul>
</body>
</html>

pharma/templates/price.html
{{price}}

pharma/templates/purchase.html
{% extends 'master.html' %}
{% block content %}


<table class="table center" style="margin-top: 40px;">
  <thead>
    <tr>
      <th scope="col">Medicine id</th>
      <th scope="col">Medicine Name</th>
      <th scope="col">Avilable Quantity</th>
      <th scope="col">Purchase Cost</th>
      <th scope="col">Selling Cost</th>
      

    </tr>
  </thead>
  <tbody>
    {% for m in medicine %}
    <tr>
      <th scope="row">{{m.id}}</th>
      <td>{{m.name | upper}}</td>
      <td>{{m.quantity}}</td>
      <td>{{m.puchase_cost}}</td>
      <td>{{m.selling_cost}}</td>
     


    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

pharma/templates/total.html
{{total_price}}